export const orderHelperAbi = [
  {
    type: "function",
    name: "AAVE_LENDING_POOL",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "SETTLEMENT",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "appData",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "borrower",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "initialize",
    inputs: [
      { name: "_owner", type: "address", internalType: "address" },
      { name: "_borrower", type: "address", internalType: "address" },
      {
        name: "_oldCollateral",
        type: "address",
        internalType: "address",
      },
      {
        name: "_oldCollateralAmount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_newCollateral",
        type: "address",
        internalType: "address",
      },
      {
        name: "_minSupplyAmount",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "_validTo", type: "uint32", internalType: "uint32" },
      { name: "_appData", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "isValidSignature",
    inputs: [
      { name: "_orderHash", type: "bytes32", internalType: "bytes32" },
      { name: "_signature", type: "bytes", internalType: "bytes" },
    ],
    outputs: [{ name: "", type: "bytes4", internalType: "bytes4" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "minSupplyAmount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "newCollateral",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "oldCollateral",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "oldCollateralAmount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "swapCollateral",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "validTo",
    inputs: [],
    outputs: [{ name: "", type: "uint32", internalType: "uint32" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "Initialized",
    inputs: [
      {
        name: "version",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "AppDataDoesNotMatch", inputs: [] },
  { type: "error", name: "BadBuyToken", inputs: [] },
  { type: "error", name: "BadParameters", inputs: [] },
  { type: "error", name: "BadReceiver", inputs: [] },
  { type: "error", name: "BadSellAmount", inputs: [] },
  { type: "error", name: "BadSellToken", inputs: [] },
  { type: "error", name: "FeeIsNotZero", inputs: [] },
  { type: "error", name: "InvalidInitialization", inputs: [] },
  { type: "error", name: "NoPartiallyFillable", inputs: [] },
  { type: "error", name: "NotEnoughBuyAmount", inputs: [] },
  { type: "error", name: "NotEnoughSupplyAmount", inputs: [] },
  { type: "error", name: "NotInitializing", inputs: [] },
  { type: "error", name: "NotLongerValid", inputs: [] },
  { type: "error", name: "NotSellOrder", inputs: [] },
  { type: "error", name: "OnlyBalanceERC20", inputs: [] },
  { type: "error", name: "OrderDoesNotMatchMessageHash", inputs: [] },
  {
    type: "error",
    name: "SafeERC20FailedOperation",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
  },
  { type: "error", name: "WrongValidTo", inputs: [] },
];
